### ISSUE TITLE
Usage without functions?

### ISSUE THREAD

**Issue by frenzymadness** [fyrestone/pycode_similar#1]
Hello.

First, thanks for your work, it's great.

I would like to use `pycode_similar` to check students' homeworks in my Python class. The problem is that the code they write is very basic at the beginning so they don't use functions.

Is there any way how to use `pycode_similar` to check files without functions? If it's possible but not implemented yet, let me know and I'll take a look at how to do it.

Thanks a lot.

**Comment by maxkraft7** [comment]
I would also like this feature to be implemented

**Comment by helenocampos** [comment]
Any news on this topic?
