### ISSUE TITLE
Am I right to define a new function for the simple command that we would like to do plagiarism check? 

### ISSUE THREAD

**Issue by tingweidaniel** [fyrestone/pycode_similar#3]
Thank you in advance for your work,

The _pycode_similar_ seems for checking the python defined function only, not applies in a simple command such as for loop and while statement.  Since I just want to use _pycode_similar_ to check the simple command, I would like to know whether I can wrap up a newly defined function for my simple command?

For example:
The following is my original simple command that we want to do the plagiarism check:
```
a = 2
for i in range(10):
    i += a
    print(i)
```

Now I wrap up a newly defined function in order to implement the plagiarism check for simple command:
```
def wrapping():
    a = 2
    for i in range(10):
        i += a
        print(i)
```

Is this method effectively to apply the _pycode_similar_ in checking simple command?
Thanks for reading.

**Comment by fyrestone** [comment]
Sorry for my late response. It's a good walk-around to wrap codes into a function. `pycode_similar` compares AST by functions. Hope `pycode_similar` could helps you.
